version: "2"

linters:
  default: standard
  disable:
    - gochecknoglobals
    - gosec
    - mnd
    - prealloc
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: github.com/davecgh/go-spew/spew
              desc: not allowed
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 130
      tab-width: 4
    revive:
      confidence: 0.8
    unparam:
      check-exported: false
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      allow-cuddle-declarations: true
      allow-trailing-comment: false
      force-case-trailing-whitespace: 0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/empregoligado/rabbids
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
