name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Go env
        run: go env

      - name: Tests
        run: go test -race -covermode=atomic -coverprofile=coverage.txt -timeout=1m -cover ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
