name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Use golint via golangci-lint binary with "warning" level.
  golint:
    name: runner / golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--disable-all -E golint"
          tool_name: golint # Change reporter name.
          level: error

  golangci-lint:
    if: github.event_name == 'pull_request'
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-golangci-lint@v1
        with:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.HUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml -D golint"
          level: "warning"
          reporter: github-pr-check

  staticcheck:
    if: github.event_name == 'pull_request'
    name: runner / staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-staticcheck@v1
        with:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.HUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-misspell@v1
        with:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.HUB_TOKEN }}
          locale: "US"
          reporter: github-check

  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-languagetool@v1
        with:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.HUB_TOKEN }}
          reporter: github-check
          level: info
          patterns: |
            **/*.md
            !**/testdata/**
