name: reviewdog

on:
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_version: v2.12.2
          golangci_lint_flags: --config=.golangci.yml -E revive -E errcheck
          reporter: github-check
          filter_mode: nofilter
